#!/bin/bash

NEW_MODEL=$(ls -t *.mod | head -n1)

if [[ -e ../models/step2_final.mod ]];then
	cp ../models/step2_final.mod ../models/step2_final.mod.old
fi

if [[ -e ${NEW_MODEL} ]];then
	echo "copy" ${NEW_MODEL} "to ../models/step2_final.mod" 
	scp ${NEW_MODEL} ../models/step2_final.mod
else
	echo "no model to copy"
	exit 1
fi
